# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  global_var: 'GLOBAL'
stages:
- stage: build
  variables:
    global_var: 'build-stage'
  displayName: Build stage
  jobs:
  - job: CI
    displayName: CI build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo Hello, world! $(global_var)
      displayName: 'Run a one-line script'
- stage: deploy
  dependsOn: build
  variables:
    stage_var: 'deploy-stage'
  jobs:
  - deployment: deployment
    variables:
      job_variable: 'job variable'
      stage_var: 'deploy override'
    displayName: Deployment
    environment: 'test'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo stage variable: $(stage_var) $(job_variable)
            displayName: 'Run a multi-line script'
